[build]
command = "hugo"
publish = "public"
[build.environment]
HUGO_VERSION = "0.84.0"

[context]
[context.branch-deploy]
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.deploy-preview]
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.production]
[context.production.environment]
HUGO_ENV = "production"

[[redirects]]
  from = "/DA-DAA"
  to = "https://www.datacamp.com/certificate/DAA0015136991877"
  status = 302
  force = true

[[redirects]]
  from = "/DA-DAP"
  to = "https://www.datacamp.com/certificate/DA0016698068691"
  status = 302
  force = true