[build]
command = "hugo"
publish = "public"
[build.environment]
HUGO_VERSION = "0.84.0"

[context]
[context.branch-deploy]
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.deploy-preview]
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.production]
[context.production.environment]
HUGO_ENV = "production"

[[redirects]]
  from = "/resume"
  to = "/resume.pdf"
  status = 200

[[redirects]]
  from = "/cv"
  to = "/resume.pdf"
  status = 200

[[redirects]]
  from = "/DA-DAA"
  to = "certs/DA-DAA.pdf"
  status = 200

[[redirects]]
  from = "/DA-DAP"
  to = "certs/DA-DAP.pdf"
  status = 200

[[redirects]]
  from = "/DA-DSA"
  to = "certs/DA-DSA.pdf"
  status = 200

 [[redirects]]
  from = "/2023-novy-zacatek"
  to = "prekvapko.webp"
  status = 200